columns: ['person_age',
  'person_income',
  'person_emp_length',
  'loan_amnt',
  'loan_int_rate',
  'loan_percent_income',
  'cb_person_cred_hist_length',
  'person_home_ownership',
  'loan_intent_DEBTCONSOLIDATION',
  'loan_intent_EDUCATION',
  'loan_intent_HOMEIMPROVEMENT',
  'loan_intent_MEDICAL',
  'loan_intent_PERSONAL',
  'loan_intent_VENTURE',
  'loan_grade_A',
  'loan_grade_B',
  'loan_grade_C',
  'loan_grade_D',
  'loan_grade_E',
  'loan_grade_F',
  'loan_grade_G',
  'cb_person_default_on_file_N',
  'cb_person_default_on_file_Y']

raw_columns: ['person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_grade', 'loan_amnt',
       'loan_int_rate', 'loan_percent_income',
       'cb_person_default_on_file', 'cb_person_cred_hist_length']

target: 'loan_status'

all_numerical_columns: ['person_age', 'person_income', 'person_emp_length', 'loan_amnt', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length']
all_ordinal_columns: ['person_home_ownership']
base_categories: ['loan_intent', 'loan_grade', 'cb_person_default_on_file']

optimizable_numerical_columns: ['person_income', 'person_emp_length', 'loan_amnt']
optimizable_ordinal_columns: ['person_home_ownership']
optimizable_categories: ['loan_intent']

recalc_params_matrix: [['person_income', 'loan_amnt', 'loan_percent_income',]]